[tools]
go = "1.27"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "latest"
golangci-lint = "2.13.1"
gotestsum = "1.13.0"

[tasks.format]
description = "Apply code formatting"
run = "golangci-lint fmt ."

[tasks.lint]
run = "golangci-lint run"

[tasks.get]
description = "Fetch dependencies"
run = "go get -t"

[tasks.test]
description = "Run tests"
run = "gotestsum -f dots-v2 ./..."

[tasks.doc-preview]
run = "pkgsite"
