name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jdx/mise-action@v2.0.2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Test
      run: go test -v ./...
